### PR TITLE
upgrade our CI images

### PR DESCRIPTION
**Pull request by igalic**
This should fix test breakage currently happening

### CODE REVIEW

**Comment by igalic** [comment]
feels like something isn't quite right
like moving from one job to the next we didn't bring our build artefacts

**Comment by igalic** [comment]
so, first off, this fails:

```sh
find target/debug -maxdepth 1 -iname 'rctl-*[^\.d]'
```

on my machine, this doesn't return anything either… and, i'm not sure what it's supposed to return!

then we have this failure:

```sh
pkg install -y kcov bash git
# Updating FreeBSD repository catalogue...
# FreeBSD repository is up to date.
# All repositories are up to date.
# pkg: No packages available to install matching 'kcov' have been found in the repositories
# Exit status: 70
```

on my system this works, so let's hope it's just temporary

**Comment by fabianfreyer** [comment]
> ```shell
> find target/debug -maxdepth 1 -iname 'rctl-*[^\.d]'
> ```

This was supposed to enumerate all the [dep-info](https://doc.rust-lang.org/cargo/guide/build-cache.html) files... But maybe we should migrate to https://github.com/kennytm/cargo-kcov?

**Comment by fabianfreyer** [comment]
Thanks a lot, @igalic !

**Pull request merged**
